# Generated by Django 5.0.1 on 2024-01-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('plan', models.TextField()),
                ('campaign', models.TextField()),
                ('option', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
                ('country', models.TextField()),
                ('zip_code', models.TextField()),
                ('state_province', models.TextField()),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
