# Generated by Django 5.0.1 on 2024-01-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name_kata',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name_kata',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='campaign',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.TextField(default='male'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='option',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state_province',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.TextField(default=''),
        ),
    ]
