# Generated by Django 5.0.1 on 2024-01-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_created_date_customer_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerKintone',
            fields=[
                ('register_date', models.DateField()),
                ('plan', models.TextField(default='')),
                ('campaign', models.TextField(default='')),
                ('option', models.TextField(default='')),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('first_name_kata', models.TextField(default='')),
                ('last_name_kata', models.TextField(default='')),
                ('gender', models.TextField(default='')),
                ('birthday', models.DateField()),
                ('country', models.TextField(default='')),
                ('zip_code', models.TextField(default='')),
                ('state_province', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('street', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
            ],
        ),
    ]
