# Generated by Django 5.0.1 on 2024-01-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customerkintone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerKintone',
        ),
    ]
